name: Test Dojo Adjacents Chars GitHub Actions
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dojo-adjacent-chars

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd dojo-adjacent-chars && npm ci

      - name: Execute unit tests
        run: cd dojo-adjacent-chars && npm test
