name: Test TypeScript with Jest POC GitHub Actions
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ts-jest-poc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Execute unit tests
        run: npm test